import os

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        current_path=os.getcwd()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(478, 850)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_18 = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(400, 100))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_18.setFont(font)
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(f"{current_path}/../resources/images/img_quangcao.jpg"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_5.addWidget(self.label_18)
        self.verticalLayout.addWidget(self.frame)
        self.frame_header_thanhtoan = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_header_thanhtoan.sizePolicy().hasHeightForWidth())
        self.frame_header_thanhtoan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.frame_header_thanhtoan.setFont(font)
        self.frame_header_thanhtoan.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_header_thanhtoan.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_header_thanhtoan.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_header_thanhtoan.setObjectName("frame_header_thanhtoan")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_header_thanhtoan)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_return = QtWidgets.QPushButton(parent=self.frame_header_thanhtoan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_return.sizePolicy().hasHeightForWidth())
        self.pushButton_return.setSizePolicy(sizePolicy)
        self.pushButton_return.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(f"{current_path}/../resources/images/icon_return.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_return.setIcon(icon)
        self.pushButton_return.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_return.setAutoDefault(False)
        self.pushButton_return.setDefault(False)
        self.pushButton_return.setFlat(True)
        self.pushButton_return.setObjectName("pushButton_return")
        self.horizontalLayout.addWidget(self.pushButton_return)
        self.label_thanhtoan = QtWidgets.QLabel(parent=self.frame_header_thanhtoan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_thanhtoan.sizePolicy().hasHeightForWidth())
        self.label_thanhtoan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_thanhtoan.setFont(font)
        self.label_thanhtoan.setObjectName("label_thanhtoan")
        self.horizontalLayout.addWidget(self.label_thanhtoan)
        self.verticalLayout.addWidget(self.frame_header_thanhtoan)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(17)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 458, 464))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.productbox = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productbox.sizePolicy().hasHeightForWidth())
        self.productbox.setSizePolicy(sizePolicy)
        self.productbox.setMinimumSize(QtCore.QSize(0, 97))
        self.productbox.setMaximumSize(QtCore.QSize(16777215, 97))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.productbox.setFont(font)
        self.productbox.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.productbox.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.productbox.setObjectName("productbox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.productbox)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.image = QtWidgets.QFrame(parent=self.productbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(90)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image.sizePolicy().hasHeightForWidth())
        self.image.setSizePolicy(sizePolicy)
        self.image.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.image.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.image.setObjectName("image")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.image)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_image = QtWidgets.QLabel(parent=self.image)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image.sizePolicy().hasHeightForWidth())
        self.label_image.setSizePolicy(sizePolicy)
        self.label_image.setText("")
        self.label_image.setPixmap(QtGui.QPixmap(f"{current_path}/../resources/images/img_banhtrangtron.png"))
        self.label_image.setScaledContents(True)
        self.label_image.setObjectName("label_image")
        self.verticalLayout_5.addWidget(self.label_image)
        self.horizontalLayout_2.addWidget(self.image)
        self.content = QtWidgets.QFrame(parent=self.productbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(186)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.content.sizePolicy().hasHeightForWidth())
        self.content.setSizePolicy(sizePolicy)
        self.content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.content.setObjectName("content")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.content)
        self.verticalLayout_6.setContentsMargins(3, 0, 0, 0)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_name = QtWidgets.QLabel(parent=self.content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_name.sizePolicy().hasHeightForWidth())
        self.label_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.verticalLayout_6.addWidget(self.label_name)
        self.textEdit_topping = QtWidgets.QTextEdit(parent=self.content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.textEdit_topping.sizePolicy().hasHeightForWidth())
        self.textEdit_topping.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.textEdit_topping.setFont(font)
        self.textEdit_topping.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.textEdit_topping.setLineWidth(0)
        self.textEdit_topping.setReadOnly(True)
        self.textEdit_topping.setCursorWidth(1)
        self.textEdit_topping.setObjectName("textEdit_topping")
        self.verticalLayout_6.addWidget(self.textEdit_topping)
        self.quantitybox = QtWidgets.QFrame(parent=self.content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.quantitybox.sizePolicy().hasHeightForWidth())
        self.quantitybox.setSizePolicy(sizePolicy)
        self.quantitybox.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.quantitybox.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.quantitybox.setObjectName("quantitybox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.quantitybox)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_minus = QtWidgets.QPushButton(parent=self.quantitybox)
        self.pushButton_minus.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(f"{current_path}/../resources/images/icon_minus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_minus.setIcon(icon1)
        self.pushButton_minus.setFlat(True)
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.horizontalLayout_3.addWidget(self.pushButton_minus)
        self.label_quantity = QtWidgets.QLabel(parent=self.quantitybox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_quantity.setFont(font)
        self.label_quantity.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_quantity.setObjectName("label_quantity")
        self.horizontalLayout_3.addWidget(self.label_quantity)
        self.pushButton_plus = QtWidgets.QPushButton(parent=self.quantitybox)
        self.pushButton_plus.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(f"{current_path}/../resources/images/icon_plus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_plus.setIcon(icon2)
        self.pushButton_plus.setFlat(True)
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.horizontalLayout_3.addWidget(self.pushButton_plus)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addWidget(self.quantitybox)
        self.horizontalLayout_2.addWidget(self.content)
        self.button = QtWidgets.QFrame(parent=self.productbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(132)
        sizePolicy.setVerticalStretch(132)
        sizePolicy.setHeightForWidth(self.button.sizePolicy().hasHeightForWidth())
        self.button.setSizePolicy(sizePolicy)
        self.button.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.button.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.button.setObjectName("button")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.button)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_delete = QtWidgets.QPushButton(parent=self.button)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.pushButton_delete.sizePolicy().hasHeightForWidth())
        self.pushButton_delete.setSizePolicy(sizePolicy)
        self.pushButton_delete.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_delete.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(f"{current_path}/../resources/images/icon_trash.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_delete.setIcon(icon3)
        self.pushButton_delete.setFlat(True)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.gridLayout.addWidget(self.pushButton_delete, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.label_price = QtWidgets.QLabel(parent=self.button)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.label_price.sizePolicy().hasHeightForWidth())
        self.label_price.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_price.setFont(font)
        self.label_price.setStyleSheet("color: rgb(189, 25, 6);")
        self.label_price.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_price.setObjectName("label_price")
        self.gridLayout.addWidget(self.label_price, 1, 0, 1, 3)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.horizontalLayout_2.addWidget(self.button)
        self.verticalLayout_2.addWidget(self.productbox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_thanhtoan_2 = QtWidgets.QLabel(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(17)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_thanhtoan_2.sizePolicy().hasHeightForWidth())
        self.label_thanhtoan_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_thanhtoan_2.setFont(font)
        self.label_thanhtoan_2.setObjectName("label_thanhtoan_2")
        self.verticalLayout_3.addWidget(self.label_thanhtoan_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_2)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.frame_2)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.pushButton.setStyleSheet("border-radius: 12px;\n"
"background-color: rgb(189, 25, 6);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 478, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_thanhtoan.setText(_translate("MainWindow", "Giỏ hàng"))
        self.label_name.setText(_translate("MainWindow", "Bánh trán trộn"))
        self.textEdit_topping.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; color:#8a8a8a;\">4 Miếng Gà + 1 Mì Ý Gà viên + 2 Ly Pepsi (vừa)</span></p></body></html>"))
        self.label_quantity.setText(_translate("MainWindow", "2"))
        self.label_price.setText(_translate("MainWindow", "168.000 đ"))
        self.label_thanhtoan_2.setText(_translate("MainWindow", "Thanh toán"))
        self.label.setText(_translate("MainWindow", "Mã Voucher"))
        self.label_2.setText(_translate("MainWindow", "Tổng thanh toán"))
        self.pushButton.setText(_translate("MainWindow", "Thanh toán"))

